bonfire_quotes/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('quotes.urls')),
]

admin.site.site_header = "Bonfire Quotes"
admin.site.site_title = "Bonfire Quotes Portal"
admin.site.index_title = "Welcome to Bonfire Quotes"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

quotes/urls.py
from django.urls import path
from .views import  PostDetailView, PostDeleteView
from . import views

urlpatterns = [
    path('', views.home, name="quotes-home"),
    path('post/<int:pk>', PostDetailView.as_view(), name="post-detail"),
    path('post/<int:pk>/update/', views.update_post, name="post-update"),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name="post-delete"),
    path('post/<int:pk>/like/<int:like_val>/', views.like_post, name='post-like'),
    path('post/new', views.create_post, name="post-create"),
    path('post/preview', views.preview_post, name="post-preview"),
    path('about/', views.about, name="quotes-about"),
    path('community/', views.community, name="quotes-community"),
]

quotes/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django import forms
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, null=True, blank=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name='children')

    class Meta:
        unique_together = ('slug', 'parent',)
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Background(models.Model):
    color = models.CharField(max_length=100, default="")
    slug = models.SlugField(unique=True, default="")

    def __str__(self):
        return self.color


class Post(models.Model):
    quote = models.CharField(max_length=200, default="")
    author = models.ForeignKey('Author', on_delete=models.CASCADE, null=True, blank=True)

    categories = models.ManyToManyField('Category', through='PostCategory')
    backgrounds = models.ManyToManyField('Background', through='PostBackground')

    draft = models.BooleanField(default=False)
    slug = models.SlugField(unique=True, null=True, blank=True)

    published = models.DateTimeField(
        default=timezone.now, 
        auto_now=False, 
        auto_now_add=False, 
        blank=True,
        unique=True
        )
    date_posted = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default="")
    likes = models.IntegerField(default=0)
    feature_qotd = models.BooleanField(default=False, verbose_name="Featured QOTD")
    featured_as_qotd = models.BooleanField(default=False, verbose_name="Has Been QOTD")

    img = models.ImageField(default='default.jpg', upload_to='quote_pics', verbose_name="Quote Img")
    img_author = models.CharField(max_length=50, default="", verbose_name="Photographer")
    img_author_url = models.URLField(max_length=100, default="", verbose_name="Photographer url")

    def __str__(self):
        return self.quote

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})


class PostForm(forms.Form):
    id = forms.CharField(max_length=100, widget=forms.HiddenInput(), required=False)
    quote = forms.CharField(label='Quote', max_length=100, min_length=10,
                            widget=forms.Textarea(attrs={'placeholder': '', 'rows': 4, 'class': 'form-control'}),
                            required=True)
    author = forms.CharField(label='Author', max_length=30,
                             widget=forms.TextInput(attrs={'placeholder': '', 'class': 'form-control'}),
                             required=True)
    category1 = forms.CharField(label='Category 1 ', max_length=15,
                                widget=forms.TextInput(attrs={'placeholder': '', 'class': 'form-control'}),
                                required=False)
    category2 = forms.CharField(label='Category 2 ', max_length=15,
                                widget=forms.TextInput(attrs={'placeholder': '', 'class': 'form-control'}),
                                required=False)
    background1 = forms.CharField(label='Background 1 ', max_length=15,
                                  widget=forms.TextInput(attrs={'placeholder': '', 'class': 'form-control colorpicker-anchor'}),
                                  required=True)
    background2 = forms.CharField(label='Background 2 ', max_length=15,
                                  widget=forms.TextInput(attrs={'placeholder': '', 'class': 'form-control colorpicker-anchor'}),
                                  required=True)

    def clean(self):
        cleaned_data = super().clean()

        posts = Post.objects.filter(quote=slugify(cleaned_data['quote'], allow_unicode=True))

        if len(posts) > 0:
            raise forms.ValidationError("The post that has same quote has already existed.")

        cate1 = cleaned_data.get("category1")
        cate2 = cleaned_data.get("category2")

        background1 = cleaned_data.get("background1")
        background2 = cleaned_data.get("background2")

        if cate1 == "" and cate2 == "":
            raise forms.ValidationError("You have to input at least one category.")

        if cate1 == cate2:
            raise forms.ValidationError("The categories should be different.")

        if background1 == background2:
            raise forms.ValidationError("The backgrounds should be different.")


class PostBackground(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    background = models.ForeignKey(Background, on_delete=models.CASCADE)


class PostCategory(models.Model):
    class Meta:
        verbose_name_plural = "post categories"

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Author(models.Model):
    name = models.CharField(max_length=100, default="")
    img = models.ImageField(default='author_default.jpg', upload_to='profile_pics')
    slug = models.SlugField(unique=True, default="")

    def __str__(self):
        return self.name


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.IntegerField()
    timestamp = models.DateField(default=timezone.now, auto_now=False, auto_now_add=False)

    def __str__(self):
        return f'{self.user.username} likes \'{self.post.quote}\''

class QuoteCollections(models.Model):
    name = models.CharField(max_length=100, default="")
    title = models.CharField(max_length=100, default="")
    img = models.ImageField(default='default.jpg', upload_to='quote_pics', verbose_name="Collection BG Img") 

    draft = models.BooleanField(default=False)
    slug = models.SlugField(unique=True, null=True, blank=True)

    published = models.DateTimeField(default=timezone.now, auto_now=False, auto_now_add=False)
    date_posted = models.DateTimeField(default=timezone.now)

    quote = models.ManyToManyField('Post')

    class Meta:
        verbose_name_plural = "Quote Collections"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(QuoteCollections, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

quotes/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post, PostForm, Author, Category, Background, Like
from django.contrib.auth.decorators import login_required
from django.utils.text import slugify
from django.urls import reverse
from django.shortcuts import redirect


def home(request):
    context = {
        'posts': Post.objects.filter(feature_qotd=True).order_by("-date_posted")
    }
    return render(request, 'quotes/home.html', context)


class PostDetailView(DetailView):
    model = Post


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['quote', 'author', 'category']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.user:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.user:
            return True
        return False


@login_required
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)

        if form.is_valid():
            author, created = Author.objects.get_or_create(
                name=form.cleaned_data['author'],
                defaults={'slug': slugify(form.cleaned_data['author'], allow_unicode=True)})

            post = Post(author=author, quote=form.cleaned_data['quote'],
                        slug=slugify(form.cleaned_data['quote'], allow_unicode=True), user=request.user)
            post.save()

            background1, created = Background.objects.get_or_create(
                color=form.cleaned_data['background1'],
                defaults={'slug': slugify(form.cleaned_data['background1'], allow_unicode=True)})

            post.backgrounds.add(background1)

            background2, created = Background.objects.get_or_create(
                color=form.cleaned_data['background2'],
                defaults={'slug': slugify(form.cleaned_data['background2'], allow_unicode=True)})

            post.backgrounds.add(background2)

            if form.cleaned_data['category1'] != "":
                category1, created = Category.objects.get_or_create(
                    name=form.cleaned_data['category1'],
                    defaults={'slug': slugify(form.cleaned_data['category1'], allow_unicode=True)})
                post.categories.add(category1)

            if form.cleaned_data['category2'] != "":
                category2, created = Category.objects.get_or_create(
                    name=form.cleaned_data['category2'],
                    defaults={'slug': slugify(form.cleaned_data['category2'], allow_unicode=True)})
                post.categories.add(category2)

            post.save()

            return redirect(reverse('quotes-home'))
    else:
        form = PostForm()

    return render(request, 'quotes/post_form.html', {'form': form})


@login_required
def preview_post(request):
    if request.method == 'POST':
        quote = request.POST.get('quote')
        author = request.POST.get('author')
        category1 = request.POST.get('category1')
        category2 = request.POST.get('category2')
        background1 = request.POST.get('background1')
        background2 = request.POST.get('background2')

        if '\n' in quote:
            quote = quote.replace('\n', '<br>')

        author = author.split()

        data = {'quote': quote, 'author': author, 'category1': category1, 'category2': category2,
                'background1': background1, 'background2': background2}

        return render(request, 'quotes/post_preview.html', data)

    else:
        return HttpResponse('')


@login_required
def update_post(request, pk):
    post = Post.objects.get(pk=pk)

    if request.method == 'POST':
        form = PostForm(request.POST)

        if form.is_valid():
            author, created = Author.objects.get_or_create(
                name=form.cleaned_data['author'],
                defaults={'slug': slugify(form.cleaned_data['author'], allow_unicode=True)})

            post.quote = form.cleaned_data['quote']
            post.author = author

            post.save()

            post.backgrounds.clear()

            background1, created = Background.objects.get_or_create(
                color=form.cleaned_data['background1'],
                defaults={'slug': slugify(form.cleaned_data['background1'], allow_unicode=True)})

            post.backgrounds.add(background1)

            background2, created = Background.objects.get_or_create(
                color=form.cleaned_data['background2'],
                defaults={'slug': slugify(form.cleaned_data['background2'], allow_unicode=True)})

            post.backgrounds.add(background2)

            post.categories.clear()

            if form.cleaned_data['category1'] != "":
                category1, created = Category.objects.get_or_create(
                    name=form.cleaned_data['category1'],
                    defaults={'slug': slugify(form.cleaned_data['category1'], allow_unicode=True)})
                post.categories.add(category1)

            if form.cleaned_data['category2'] != "":
                category2, created = Category.objects.get_or_create(
                    name=form.cleaned_data['category2'],
                    defaults={'slug': slugify(form.cleaned_data['category2'], allow_unicode=True)})
                post.categories.add(category2)

            post.save()

            return redirect(reverse('quotes-home'))
    else:
        categories = post.categories.all()
        backgrounds = post.backgrounds.all()

        if 2 == len(categories):
            category1 = categories[0].name
            category2 = categories[1].name
        elif len(categories) == 1:
            category1 = categories[0].name
            category2 = ""
        else:
            category1 = ""
            category2 = ""

        if len(backgrounds) == 2:
            background1 = backgrounds[0].color
            background2 = backgrounds[1].color
        elif len(categories) == 1:
            background1 = backgrounds[0].color
            background2 = ""
        else:
            background1 = ""
            background2 = ""

        form = PostForm(
            initial={'id': post.id, 'author': post.author.name, 'quote': post.quote, 'category1': category1,
                     'category2': category2,
                     'background1': background1, 'background2': background2})

    return render(request, 'quotes/post_form.html', {'form': form})


@login_required
def like_post(request, pk, like_val):
    if request.method == "POST":
        post = get_object_or_404(Post, id=pk)
        try:
            like = Like.objects.get(user=request.user, post=post)

            if like.value != like_val:
                like.delete()

                new_like = Like()

                new_like.user = request.user
                new_like.post = post
                new_like.value = like_val

                if like_val == 1 and like.value != 1:
                    post.likes += 1
                elif like_val == 0 and like.value != 0:
                    post.likes -= 1
                    if post.likes <= 0:
                        post.likes = 0

                new_like.save()

                post.save()

                return redirect(reverse('quotes-home'))

        except Like.DoesNotExist:
            new_like = Like()

            new_like.user = request.user
            new_like.post = post
            new_like.value = like_val

            new_like.save()

            if like_val == 1:
                post.likes += 1
                post.save()

        return redirect(reverse('quotes-home'))


def about(request):
    return render(request, 'quotes/about.html')


def community(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'quotes/community.html', context)

quotes/templates/quotes/about.html
{% extends "quotes/base.html" %}
{% block content %}
    <h1>About us page</h1>
{% endblock content %}

quotes/templates/quotes/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
    <!--CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'quotes/light.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'quotes/main.css' %}" />
    <!--CSS-->
    {% if title %}
    <title>Bonfire Quotes - {{ title }}</title>
    {% else %}
    <title>Bonfire Quotes</title>
    {% endif %} {% block header %}{% endblock %}
</head>

<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="{% url 'quotes-home' %}">
                    <img src="{% static 'quotes/Bonfire_logo.png' %}" alt="Bonfire Quotes" height="45px" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto"></div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        <a class="nav-item nav-link" href="{% url 'quotes-community' %}">Community</a
              >
              {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'post-create' %}"
                >New Quote</a
              >
              <a class="nav-item nav-link" href="{% url 'profile' %}"
                >Profile</a
              >
              <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a> {% else %}
                        <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                        <a class="nav-item nav-link" href="{% url 'register' %}">Sign Up</a
              >
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-12">
          {% if messages %} {% for message in messages %}
          <div class="alert alert-{{ message.tags }} ">
            {{ message }}
          </div>
          {% endfor %} {% endif %} {% block content %}{% endblock %}
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script
      src="{% static 'quotes/default-picker.min.js' %}"
      type="text/javascript"
    ></script>
    {% block footerscript %}{% endblock %}
  </body>
</html>

quotes/templates/quotes/home.html
{% extends "quotes/base.html" %} {% load like %} {% load static %} {% block content %} {% for post in posts %}
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ post.user.profile.image.url }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="#">{{ post.user }}
                        {#                &&#}
                        {#                {% for category in post.categories.all %}#}
                        {#                    {{ category.name }}#}
                        {#                {% endfor %}#}
                    </a>
            <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
        </div>
        <h2><a class="article-title" href="{% url 'post-detail' post.id %}">" {{ post.quote }} "</a></h2>
        <p class="article-content" style="line-height: 15px">
            Author: {{ post.author }} <br/> Like: {{ post.likes }} {# {% if post.feature_qotd %}#} {# Featured <i class="fa fa-check"></i>#} {# {% endif %}#} {% if user.is_authenticated %} {% get_like post as like %} {% if like.value == 0 %}
            <a href="#" onClick="document.getElementById('likebutton{{ post.id }}').submit()" class="btn btn-primary px-2 mr-1" style="float:right">
                <img src="{% static 'quotes/fire_icon.png' %}" style="width: 20px; height:30px;">
            </a>
            {% elif like.value == 1 %}
            <a href="#" onClick="document.getElementById('dislikebutton{{ post.id }}').submit()" class="btn btn-danger px-2" style="float:right">
                <img src="{% static 'quotes/fire_icon.png' %}" style="width: 20px; height:30px;">
            </a>
            {% else %}
            <a href="#" onClick="document.getElementById('likebutton{{ post.id }}').submit()" class="btn btn-primary px-2 mr-1" style="float:right">
                <img src="{% static 'quotes/fire_icon.png' %}" style="width: 20px; height:30px;">
            </a>
            {% endif %}
            <form id="likebutton{{ post.id }}" method="POST" action="{% url 'post-like' post.id 1 %}">
                {% csrf_token %}
                <input type="hidden">
            </form>
            <form id="dislikebutton{{ post.id }}" method="POST" action="{% url 'post-like' post.id 0 %}">
                {% csrf_token %}
                <input type="hidden">
            </form>
            {% endif %}
        </p>
    </div>
</article>
{% endfor %} {% endblock content %}

quotes/templates/quotes/post_form.html
{% extends "quotes/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block header %}
    <style>
        body {
            background: linear-gradient(to bottom, #ebe6e8 0%, #b6ceac 90%) !important;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="row inner-bon">
    <div class="col-md-6 nopadding">
        <div class="left-back"></div>
    </div>
    <div class="col-md-6">
        <div class="right-bon">
            <form method="POST">
                {% csrf_token %}
                {% if form.non_field_errors %}
                    <div class="form-row">
                        <div class="valid-feedback" style="display: block">
                            {% for error in form.non_field_errors %}
                                <p class="form-error">{{ error|escape }}</p>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
                <h2 class="newquote-title">New Quote</h2>
                <div class="form-group">
                    <label for="{{ form.quote.id_for_label }}"><b>Quote *: </b></label>
                    {{ form.quote }}
                    {% if form.quote.errors %}
                        <div class="valid-feedback" style="display: block">
                            {% for error in form.quote.errors %}
                                <p class="form-error">{{ error|escape }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="{{ form.author.id_for_label }}"><b>Author *:</b></label>
                    {{ form.author }}
                    {% if form.author.errors %}
                        <div class="valid-feedback" style="display: block">
                            {% for error in form.author.errors %}
                                <p class="form-error">{{ error|escape }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="{{ form.category1.id_for_label }}"><b>Category1 :</b></label>
                        {{ form.category1 }}
                        {% if form.category1.errors %}
                            <div class="valid-feedback" style="display: block">
                                {% for error in form.category1.errors %}
                                    <p class="form-error">{{ error|escape }}</p>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                    <div class="form-group col-md-6">
                        <label for="{{ form.category2.id_for_label }}"><b>Category2 :</b></label>
                        {{ form.category2 }}
                        {% if form.category2.errors %}
                            <div class="valid-feedback" style="display: block">
                                {% for error in form.category2.errors %}
                                    <p class="form-error">{{ error|escape }}</p>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        {{ form.background1.errors }}
                        <label for="{{ form.background1.id_for_label }}"><b>Background1 :</b></label>
                        <span class="colorpicker-input colorpicker-input--position-right">
                            {{ form.background1 }}
                            <span id="background1-toggle" class="colorpicker-custom-anchor colorpicker-circle-anchor">
                              <span class="colorpicker-circle-anchor__color" data-color=""></span>
                            </span>
                        </span>
                        {% if form.background1.errors %}
                            <div class="valid-feedback" style="display: block">
                                {% for error in form.background1.errors %}
                                    <p class="form-error">{{ error|escape }}</p>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                    <div class="form-group col-md-6">
                        <label for="{{ form.background2.id_for_label }}"><b>Backgrond2 :</b></label>
                        <span class="colorpicker-input colorpicker-input--position-right">
                            {{ form.background2 }}
                            <span id="background2-toggle" class="colorpicker-custom-anchor colorpicker-circle-anchor">
                                  <span class="colorpicker-circle-anchor__color" data-color=""></span>
                            </span>
                        </span>
                        {% if form.background2.errors %}
                            <div class="valid-feedback" style="display: block">
                                {% for error in form.background2.errors %}
                                    <p class="form-error">{{ error|escape }}</p>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="form-group mt-3">
                    <button class="btn btn-block btn-lg preview-btn" href="JavaScript:Void(0);">
                        <i>Preview</i></button>
                </div>
                <div class="form-group mt-4">
                    <button class="btn btn-primary btn-block btn-lg" type="submit">Post</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

{% block footerscript %}
    <div class="modal fade" id="preview_modal">
        <div class="modal-dialog modal-dialog-centered" id='preview_data'></div>
    </div>
    <script type="text/javascript">
        $(function () {
            var colorpickerInsideInputAnchor = $('#background1-toggle').find('[data-color]');
            var colorPickerDefaultInsideInput = new ColorPicker.Default('#id_background1', {
                hexOnly: true,
                color: $("#id_background1").val()
            });
            colorpickerInsideInputAnchor.css('background', colorPickerDefaultInsideInput.getColor());
            colorPickerDefaultInsideInput.on('change', function (color) {
                colorpickerInsideInputAnchor.css('background', color);
            });
            colorpickerInsideInputAnchor.on('click', function () {
                $('#id_background1').trigger('focus');

                return false;
            });

            var colorpickerInsideInputAnchor = $('#background2-toggle').find('[data-color]');
            var colorPickerDefaultInsideInput = new ColorPicker.Default('#id_background2', {
                hexOnly: true,
                color: $("#id_background2").val()
            });
            colorpickerInsideInputAnchor.css('background', colorPickerDefaultInsideInput.getColor());
            colorPickerDefaultInsideInput.on('change', function (color) {
                colorpickerInsideInputAnchor.css('background', color);
            });
            colorpickerInsideInputAnchor.on('click', function () {
                $('#id_background2').trigger('focus');

                return false;
            });
        })
        $(".preview-btn").click(function (e) {
            e.preventDefault();
            var quote = $('#{{ form.quote.id_for_label }}').val();
            var author = $('#{{ form.author.id_for_label }}').val();
            var category1 = $('#{{form.category1.id_for_label}}').val();
            var category2 = $('#{{form.category2.id_for_label}}').val();
            var background1 = $('#{{form.background1.id_for_label}}').val();
            var background2 = $('#{{form.background2.id_for_label}}').val();

            $.ajax(
                {
                    url: "{% url 'post-preview' %}",
                    type: 'POST',
                    data: {
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        author: author,
                        quote: quote,
                        background1: background1,
                        background2: background2,
                        category1: category1,
                        category2: category2
                    },
                    success: function (result) {
                        $('#preview_modal').modal('show');
                        $("#preview_data").html(result);
                    }
                });
        })
    </script>
{% endblock footerscript %}